
REM VFE ORGANISMO_PK

  CREATE UNIQUE INDEX "VFE"."ORGANISMO_PK" ON "VFE"."ORGANISMO" ("ID_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI1" 
REM VFE REGISTRO_DOCUMENTO_PK

  CREATE UNIQUE INDEX "VFE"."REGISTRO_DOCUMENTO_PK" ON "VFE"."REGISTRO_DOCUMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI1" 
REM VFE SYS_C0085377

  CREATE UNIQUE INDEX "VFE"."SYS_C0085377" ON "VFE"."USUARIO" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI1" 
REM VFE ORGANISMO_SEQ

   CREATE SEQUENCE  "VFE"."ORGANISMO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 425 CACHE 20 NOORDER  NOCYCLE 
REM VFE REGISTRO_DOCUMENTO_SEQ

   CREATE SEQUENCE  "VFE"."REGISTRO_DOCUMENTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 12121 CACHE 20 NOORDER  NOCYCLE 
REM VFE ORGANISMO_TRG

  CREATE OR REPLACE TRIGGER "VFE"."ORGANISMO_TRG" 
BEFORE INSERT ON ORGANISMO
FOR EACH ROW
BEGIN
  SELECT ORGANISMO_SEQ.NEXTVAL INTO :NEW.ID_ORG FROM DUAL;
END;


ALTER TRIGGER "VFE"."ORGANISMO_TRG" ENABLE
REM VFE REGISTRO_DOCUMENTO_TRG

  CREATE OR REPLACE TRIGGER "VFE"."REGISTRO_DOCUMENTO_TRG" 
BEFORE INSERT ON REGISTRO_DOCUMENTO
FOR EACH ROW
BEGIN
  SELECT REGISTRO_DOCUMENTO_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

ALTER TRIGGER "VFE"."REGISTRO_DOCUMENTO_TRG" ENABLE