
REM SITAE CENTRO_PROCEDENCIA_PK

  CREATE UNIQUE INDEX "SITAE"."CENTRO_PROCEDENCIA_PK" ON "SITAE"."CENTRO_PROCEDENCIA" ("ID_CENTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE CONFIGURACION_PK

  CREATE UNIQUE INDEX "SITAE"."CONFIGURACION_PK" ON "SITAE"."CONFIGURACION" ("PARAMETRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE EDICTO_PK

  CREATE UNIQUE INDEX "SITAE"."EDICTO_PK" ON "SITAE"."EDICTO" ("ID_EDICTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE ESTADO_PK

  CREATE UNIQUE INDEX "SITAE"."ESTADO_PK" ON "SITAE"."ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE FESTIVO_INDEX1

  CREATE INDEX "SITAE"."FESTIVO_INDEX1" ON "SITAE"."FESTIVO" ("NOMBRE", "ID_FESTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE FESTIVO_PK

  CREATE UNIQUE INDEX "SITAE"."FESTIVO_PK" ON "SITAE"."FESTIVO" ("ID_FESTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE FUNCIONALIDAD_PK

  CREATE UNIQUE INDEX "SITAE"."FUNCIONALIDAD_PK" ON "SITAE"."FUNCIONALIDAD" ("ID_FUNCIONALIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE INTERESADO_PK

  CREATE UNIQUE INDEX "SITAE"."INTERESADO_PK" ON "SITAE"."INTERESADO" ("ID_INTERESADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE INTERESADO_UK1

  CREATE UNIQUE INDEX "SITAE"."INTERESADO_UK1" ON "SITAE"."INTERESADO" ("EMAIL", "ID_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE ORGANISMO_EXTERNO_PK

  CREATE UNIQUE INDEX "SITAE"."ORGANISMO_EXTERNO_PK" ON "SITAE"."ORGANISMO_EXTERNO" ("ID_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE ORGANISMO_PK

  CREATE UNIQUE INDEX "SITAE"."ORGANISMO_PK" ON "SITAE"."ORGANISMO" ("ID_ORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE PERFIL_PK

  CREATE UNIQUE INDEX "SITAE"."PERFIL_PK" ON "SITAE"."PERFIL" ("ID_PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE PUBLICACION_REDES_SOCIALE_PK

  CREATE UNIQUE INDEX "SITAE"."PUBLICACION_REDES_SOCIALE_PK" ON "SITAE"."PUBLICACION_REDES_SOCIALES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE RED_SOCIAL_PK

  CREATE UNIQUE INDEX "SITAE"."RED_SOCIAL_PK" ON "SITAE"."RED_SOCIAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE RELACION_EDICTOS_PK

  CREATE UNIQUE INDEX "SITAE"."RELACION_EDICTOS_PK" ON "SITAE"."RELACION_EDICTOS" ("ID_RELACION_EDICTOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE RELACION_PERFIL_FUNCIONAL_PK

  CREATE UNIQUE INDEX "SITAE"."RELACION_PERFIL_FUNCIONAL_PK" ON "SITAE"."RELACION_PERFIL_FUNCIONALIDAD" ("ID_RELACION_PERF_FUNC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE RELACION_USU_ORG_CENTRO_P_PK

  CREATE UNIQUE INDEX "SITAE"."RELACION_USU_ORG_CENTRO_P_PK" ON "SITAE"."RELACION_USU_ORG_CENTRO_PERF" ("ID_RELACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE TIPO_EDICTO_PK

  CREATE UNIQUE INDEX "SITAE"."TIPO_EDICTO_PK" ON "SITAE"."TIPO_EDICTO" ("ID_TIPO_EDICTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE TIPO_FIRMA_PK

  CREATE UNIQUE INDEX "SITAE"."TIPO_FIRMA_PK" ON "SITAE"."TIPO_FIRMA" ("ID_TIPO_FIRMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE USUARIO_FIRMANTE_PK

  CREATE UNIQUE INDEX "SITAE"."USUARIO_FIRMANTE_PK" ON "SITAE"."USUARIO_FIRMANTE" ("ID_USUARIO_FIRMANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE USUARIO_PK

  CREATE UNIQUE INDEX "SITAE"."USUARIO_PK" ON "SITAE"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLI2" 
REM SITAE CIFRADO

  CREATE OR REPLACE PACKAGE "SITAE"."CIFRADO" IS
  function encripta(datos in varchar2)    return varchar2;
  function desencripta(datos in varchar2)   return varchar2;
end;
CREATE OR REPLACE PACKAGE BODY "SITAE"."CIFRADO" IS
FUNCTION encripta (datos in varchar2)    return varchar2
IS
BEGIN
  IF datos is NULL THEN
       RETURN NULL;
  ELSE
    RETURN DBMS_OBFUSCATION_TOOLKIT.DESENCRYPT(INPUT_STRING=>RPAD(DATOS,(TRUNC(LENGTH(DATOS)/8)+1)*8,CHR(0)),KEY_STRING=>'ADUACIFR');
  END IF;
END;
FUNCTION desencripta (datos in varchar2)    return varchar2
IS
BEGIN
  IF datos is NULL THEN
       RETURN NULL;
  ELSE
        RETURN RTRIM(DBMS_OBFUSCATION_TOOLKIT.DESDECRYPT(INPUT_STRING=>DATOS,KEY_STRING=>'ADUACIFR'),CHR(0));
  END IF;
END;
END;
REM SITAE CENTRO_PROCEDENCIA_SEQ

   CREATE SEQUENCE  "SITAE"."CENTRO_PROCEDENCIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1000 START WITH 1880 CACHE 20 NOORDER  NOCYCLE 
REM SITAE EDICTO_SEQ

   CREATE SEQUENCE  "SITAE"."EDICTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 24518 CACHE 20 NOORDER  NOCYCLE 
REM SITAE FESTIVO_SEQ

   CREATE SEQUENCE  "SITAE"."FESTIVO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 922 CACHE 20 NOORDER  NOCYCLE 
REM SITAE FUNCIONALIDAD_SEQ

   CREATE SEQUENCE  "SITAE"."FUNCIONALIDAD_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE 
REM SITAE INTERESADO_SEQ

   CREATE SEQUENCE  "SITAE"."INTERESADO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 50 NOCACHE  NOORDER  NOCYCLE 
REM SITAE ORGANISMO_EXTERNO_SEQ

   CREATE SEQUENCE  "SITAE"."ORGANISMO_EXTERNO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE 
REM SITAE ORGANISMO_SEQ

   CREATE SEQUENCE  "SITAE"."ORGANISMO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1221 CACHE 20 NOORDER  NOCYCLE 
REM SITAE PERFIL_SEQ

   CREATE SEQUENCE  "SITAE"."PERFIL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE 
REM SITAE PUBLICACION_REDES_SOCIALES_SEQ

   CREATE SEQUENCE  "SITAE"."PUBLICACION_REDES_SOCIALES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2780 NOCACHE  NOORDER  NOCYCLE 
REM SITAE RED_SOCIAL_SEQ

   CREATE SEQUENCE  "SITAE"."RED_SOCIAL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE 
REM SITAE RELACION_EDICTOS_SEQ

   CREATE SEQUENCE  "SITAE"."RELACION_EDICTOS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE 
REM SITAE RELACION_PERFIL_FUNCIONAL_SEQ

   CREATE SEQUENCE  "SITAE"."RELACION_PERFIL_FUNCIONAL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 261 CACHE 20 NOORDER  NOCYCLE 
REM SITAE RELACION_SEQ

   CREATE SEQUENCE  "SITAE"."RELACION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3287 CACHE 20 NOORDER  NOCYCLE 
REM SITAE TIPO_EDICTO_SEQ

   CREATE SEQUENCE  "SITAE"."TIPO_EDICTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 541 CACHE 20 NOORDER  NOCYCLE 
REM SITAE TIPO_FIRMA_SEQ

   CREATE SEQUENCE  "SITAE"."TIPO_FIRMA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE 
REM SITAE USUARIO_FIRMANTE_SEQ

   CREATE SEQUENCE  "SITAE"."USUARIO_FIRMANTE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE 
REM SITAE USUARIO_SEQ

   CREATE SEQUENCE  "SITAE"."USUARIO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1927 CACHE 20 NOORDER  NOCYCLE 
REM SITAE CENTRO_PROCEDENCIA_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."CENTRO_PROCEDENCIA_TRG" 
BEFORE INSERT ON CENTRO_PROCEDENCIA
FOR EACH ROW
BEGIN
  SELECT CENTRO_PROCEDENCIA_SEQ.NEXTVAL INTO :NEW.ID_CENTRO FROM DUAL;
END;





ALTER TRIGGER "SITAE"."CENTRO_PROCEDENCIA_TRG" ENABLE
REM SITAE FESTIVO_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."FESTIVO_TRG" 
BEFORE INSERT ON FESTIVO
FOR EACH ROW
BEGIN
  SELECT FESTIVO_SEQ.NEXTVAL INTO :NEW.ID_FESTIVO FROM DUAL;
END;





ALTER TRIGGER "SITAE"."FESTIVO_TRG" ENABLE
REM SITAE FUNCIONALIDAD_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."FUNCIONALIDAD_TRG" 
BEFORE INSERT ON FUNCIONALIDAD
FOR EACH ROW
BEGIN
  SELECT FUNCIONALIDAD_SEQ.NEXTVAL INTO :NEW.ID_FUNCIONALIDAD FROM DUAL;
END;





ALTER TRIGGER "SITAE"."FUNCIONALIDAD_TRG" DISABLE
REM SITAE ORGANISMO_EXTERNO_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."ORGANISMO_EXTERNO_TRG" 
BEFORE INSERT ON ORGANISMO_EXTERNO
FOR EACH ROW
BEGIN
  SELECT ORGANISMO_EXTERNO_SEQ.NEXTVAL INTO :NEW.ID_ORG FROM DUAL;
END;





ALTER TRIGGER "SITAE"."ORGANISMO_EXTERNO_TRG" ENABLE
REM SITAE ORGANISMO_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."ORGANISMO_TRG" 
BEFORE INSERT ON ORGANISMO
FOR EACH ROW
BEGIN
  SELECT ORGANISMO_SEQ.NEXTVAL INTO :NEW.ID_ORG FROM DUAL;
END;





ALTER TRIGGER "SITAE"."ORGANISMO_TRG" ENABLE
REM SITAE PERFIL_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."PERFIL_TRG" 
BEFORE INSERT ON PERFIL
FOR EACH ROW
BEGIN
  SELECT PERFIL_SEQ.NEXTVAL INTO :NEW.ID_PERFIL FROM DUAL;
END;





ALTER TRIGGER "SITAE"."PERFIL_TRG" ENABLE
REM SITAE RELACION_EDICTOS_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."RELACION_EDICTOS_TRG" 
BEFORE INSERT ON RELACION_EDICTOS
FOR EACH ROW
BEGIN
  SELECT RELACION_EDICTOS_SEQ.NEXTVAL INTO :NEW.ID_RELACION_EDICTOS FROM DUAL;
END;





ALTER TRIGGER "SITAE"."RELACION_EDICTOS_TRG" ENABLE
REM SITAE RELACION_PERFIL_FUNCIONAL_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."RELACION_PERFIL_FUNCIONAL_TRG" 
BEFORE INSERT ON RELACION_PERFIL_FUNCIONALIDAD
FOR EACH ROW
BEGIN
  SELECT RELACION_PERFIL_FUNCIONAL_SEQ.NEXTVAL INTO :NEW.ID_RELACION_PERF_FUNC FROM DUAL;
END;





ALTER TRIGGER "SITAE"."RELACION_PERFIL_FUNCIONAL_TRG" ENABLE
REM SITAE RELACION_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."RELACION_TRG" 
BEFORE INSERT ON RELACION_USU_ORG_CENTRO_PERF
FOR EACH ROW
BEGIN
  SELECT RELACION_SEQ.NEXTVAL INTO :NEW.ID_RELACION FROM DUAL;
END;





ALTER TRIGGER "SITAE"."RELACION_TRG" ENABLE
REM SITAE TIPO_FIRMA_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."TIPO_FIRMA_TRG" 
BEFORE INSERT ON TIPO_FIRMA
FOR EACH ROW
BEGIN
  SELECT TIPO_FIRMA_SEQ.NEXTVAL INTO :NEW.ID_TIPO_FIRMA FROM DUAL;
END;





ALTER TRIGGER "SITAE"."TIPO_FIRMA_TRG" ENABLE
REM SITAE USUARIO_FIRMANTE_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."USUARIO_FIRMANTE_TRG" 
BEFORE INSERT ON USUARIO_FIRMANTE
FOR EACH ROW
BEGIN
  SELECT USUARIO_FIRMANTE_SEQ.NEXTVAL INTO :NEW.ID_USUARIO_FIRMANTE FROM DUAL;
END;





ALTER TRIGGER "SITAE"."USUARIO_FIRMANTE_TRG" ENABLE
REM SITAE USUARIO_TRG

  CREATE OR REPLACE TRIGGER "SITAE"."USUARIO_TRG" 
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
  SELECT USUARIO_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END;





ALTER TRIGGER "SITAE"."USUARIO_TRG" ENABLE